[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.cjs"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.env]
NODE_ENV = "production"